title: 곰탱이의 블로그
author: GitHub User

email: your-email@domain.com
description: 바보 학생 개발자의 블로그!
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: 곰탱이
  tagline: 코딩 못하는 바보 학생 개발자
  date_format: "%Y년 %m월 %d일"
  style: black

  # generate social links in footer
  social_links:
    twitter: angrycutebear
    github:  angrycutebear
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
